Feat/download
zanurban/spletna-ucilnica pull request #42
Opened 2023-10-05 16:23 UTC by majzabukovnik

2023-10-05 17:17 UTC, majzabukovnik commented on app/Http/Controllers/FileDownloadController.php
> +                'Content-Disposition' => 'attachment; filename="' . $filename . '"',
You can change this if you want to have different name of downloaded file form what it was saved on server as

2023-10-05 17:18 UTC, majzabukovnik commented
@zanurban Please extensively test download of all kinds of files and from student and teacher accounts. If something doesn't work you can fix it yourself or open a new issue. DO NOT MERGE UNTIL IT WORKS 100%!

2023-10-05 17:22 UTC, majzabukovnik commented
Routes for file download are not protected because this somehow breaks functionality.

2023-10-05 18:17 UTC, zanurban requested changes
Donloading of files does not work for me even 
![image](https://github.com/zanurban/spletna-ucilnica/assets/113106345/23d9d40b-14f1-4e67-b72f-59f5d56816e5)

2023-10-08 15:33 UTC, zanurban commented
@majzabukovnik Please check if everything works, fix the opened issue and check for register errors (if there are any)

2023-10-08 18:07 UTC, majzabukovnik reviewed
I approve, but cannot confirm since I opened this request myself.

2023-10-08 18:38 UTC, zanurban approved these changes

2023-10-08 18:39 UTC, merged